--ROLLBACK
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE INSIS_SGI_DEV.DATA_MANIPULATOR';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

DELETE FROM INSIS_SGI_DEV.SGI_DICT_PARAMETERS WHERE PARAM_ID IN ('DATA_MAN_MAIL_LIST', 'DATA_MAN_TEXT', 'DATA_MAN_REP_PATH', 'DATA_MAN_URL_PATH')
/

--UPDATE
DECLARE
l_host_name VARCHAR2(100);
l_folder VARCHAR2(300);
BEGIN
	SELECT host_name
    INTO l_host_name
    FROM v$instance;
	
	IF upper(l_host_name) = upper('prod-insis-db01')
    THEN
		l_folder := '\\rb-ins.ru/services/INSIS_PROD/INSIS/some_extaction_for_check/';
	ELSE 
		l_folder := '\\t2-insis-as01/INSIS/manual_extraction/some_extaction_for_check/';
    END IF;  
	INSERT INTO INSIS_SGI_DEV.SGI_DICT_PARAMETERS (PARAM_ID, PARAM_VALUE, UPDATED_BY, UPDATED_DATE) 
	VALUES('DATA_MAN_REP_PATH', l_folder, 'LIQUIBASE', 
	TIMESTAMP '2023-12-07 10:21:39.000000');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

DECLARE
l_environment VARCHAR2(1000);
BEGIN
	SELECT DISTINCT TRIM(UPPER(host_name)) INTO l_environment
	FROM v$instance;
	
	IF l_environment = 'prod-insis-db01'
	THEN
		INSERT INTO INSIS_SGI_DEV.SGI_DICT_PARAMETERS (PARAM_ID, PARAM_VALUE, UPDATED_BY, UPDATED_DATE) 
		VALUES('DATA_MAN_URL_PATH', 'file:////rb-ins.ru/services/INSIS_PROD/INSIS/manual_extraction/some_extaction_for_check/', 'LIQUIBASE', 
		TIMESTAMP '2023-12-07 10:21:39.000000');
	ELSE
		INSERT INTO INSIS_SGI_DEV.SGI_DICT_PARAMETERS (PARAM_ID, PARAM_VALUE, UPDATED_BY, UPDATED_DATE) 
		VALUES('DATA_MAN_URL_PATH', 'file:////t2-insis-as01/INSIS/manual_extraction/some_extaction_for_check/', 'LIQUIBASE', 
		TIMESTAMP '2023-12-07 10:21:39.000000');
	END IF;
END;
/

DECLARE
    l_host_name      VARCHAR2(4000);
BEGIN
    SELECT host_name
      INTO l_host_name
      FROM v$instance;

    IF upper(l_host_name) != upper('prod-insis-db01')
    THEN
        INSERT INTO INSIS_SGI_DEV.SGI_DICT_PARAMETERS (PARAM_ID, PARAM_VALUE, UPDATED_BY, UPDATED_DATE) 
		VALUES('DATA_MAN_MAIL_LIST', 'a.chizhov@bestdoctor.ru', 'LIQUIBASE', 
		TIMESTAMP '2023-12-07 10:21:39.000000');
	ELSE
        INSERT INTO INSIS_SGI_DEV.SGI_DICT_PARAMETERS (PARAM_ID, PARAM_VALUE, UPDATED_BY, UPDATED_DATE) 
		VALUES('DATA_MAN_MAIL_LIST', 'a.chizhov@bestdoctor.ru', 'LIQUIBASE', 
		TIMESTAMP '2023-12-07 10:21:39.000000');
    END IF;
	INSERT INTO INSIS_SGI_DEV.SGI_DICT_PARAMETERS (PARAM_ID, PARAM_VALUE, UPDATED_BY, UPDATED_DATE) 
	VALUES('DATA_MAN_TEXT', 'Маскирование данных', 'LIQUIBASE', TIMESTAMP '2023-12-07 10:21:39.000000');
END;
/

BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE INSIS_SGI_DEV.DATA_MANIPULATOR (	"OP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MAN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPERATION_TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	"DATE_TO_EXECUTE" DATE DEFAULT trunc(SYSDATE) NOT NULL ENABLE, 
	"DATE_EXECUTION" DATE, 
	"STATUS" VARCHAR2(1) DEFAULT ''P'' NOT NULL ENABLE, 
	"REQUESTED_BY" VARCHAR2(500) DEFAULT SYS_CONTEXT( ''INSISCTX'', ''USERNAME'' ) NOT NULL ENABLE, 
	"REQUEST_REASON" VARCHAR2(500), 
	"REGISTRATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"INITIATOR_TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	"APPROVED" VARCHAR2(1) DEFAULT ''N'' NOT NULL ENABLE, 
	"DATE_OF_APPROVAL" DATE, 
	"USER_APPROVAL_1" VARCHAR2(500), 
	"DATE_APP_BY_USER_1" DATE, 
	"USER_APPROVAL_2" VARCHAR2(500), 
	"DATE_APP_BY_USER_2" DATE, 
	"USER_APPROVAL_3" VARCHAR2(500), 
	"DATE_APP_BY_USER_3" DATE, 
	"CANCELLING_REASON" VARCHAR2(1000), 
	"CANCELLED_BY_USER" VARCHAR2(500), 
	"DATE_OF_CANCELLATION" DATE, 
	 PRIMARY KEY ("OP_ID"))';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE USER INSIS_GDPR IDENTIFIED BY Ins#1Gen
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
/

GRANT CONNECT,RESOURCE TO INSIS_GDPR
/

GRANT CREATE SYNONYM, CREATE VIEW TO INSIS_GDPR
/

GRANT UNLIMITED TABLESPACE TO INSIS_GDPR
/

GRANT ALL ON INSIS_SYS_V10.SRV_LABELS TO INSIS_CUST
/
GRANT ALL ON INSIS_SYS_V10.srv_event_list TO INSIS_CUST
/
CREATE synonym insis_cust.srv_labels FOR INSIS_SYS_V10.srv_labels
/
CREATE synonym insis_cust.srv_event_list FOR INSIS_SYS_V10.srv_event_list
/
GRANT ALL ON INSIS_UL_V10.UL_UNIT_PRICES TO INSIS_CUST WITH GRANT OPTION
/
GRANT ALL ON INSIS_UL_V10.INV_REQUEST_DETAILS TO INSIS_CUST WITH GRANT OPTION
/
GRANT ALL ON INSIS_UL_V10.UL_OPERATION_TRANSACTIONS TO INSIS_CUST WITH GRANT OPTION
/
GRANT ALL ON INSIS_SGI_DEV.SGI_UL_INVESTMENT_RESULT TO INSIS_CUST WITH GRANT OPTION
/
GRANT ALL ON INSIS_UL_V10.UL_FUNDS TO INSIS_CUST WITH GRANT OPTION
/
GRANT ALL ON INSIS_UL_V10.INV_REQUEST TO INSIS_CUST WITH GRANT OPTION
/
GRANT ALL ON insis_gdpr.cfg_excluded_people TO  INSIS_HLT_V10_RLS
/
GRANT ALL ON INSIS_CUST.VW_MV_DWH_PDN_MAN_ID TO INSIS_GDPR
/
DECLARE
    l_implement_type insis_gen_v10_util.cfg_security_views.implement_type%TYPE := 'GEN';
    l_security_grp insis_gen_v10_util.cfg_security_views.security_grp%TYPE := 'BASE';
    l_err_msg VARCHAR2(32000);
BEGIN
    IF NOT insis_gen_v10_util.rls_functions.reconcile_RLS(l_implement_type, l_security_grp, l_err_msg)
    THEN
        dbms_output.put_line(l_err_msg);
        raise_application_error(-20999, 'Renconcile RLS error: ' || l_err_msg);
    END IF;
     
    dbms_output.put_line('Success');
END;
/


